[package]
name = "pacing"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pacing"
path = "src/main.rs"

[dependencies]
common = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
redis = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
